version: 2
updates:
#######################################################
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 25
    # versioning-strategy: increase
    allow:
      - dependency-name: "nestia"
      - dependency-name: "@nestia/*"
      - dependency-name: "@nestjs/*"
      - dependency-name: "@prisma/*"
      - dependency-name: "prisma"
      - dependency-name: "prisma-markdown"
      - dependency-name: "tstl"
      - dependency-name: "typia"
      - dependency-name: "tgrid"
      - dependency-name: "typescript"
      - dependency-name: "ts-patch"
    groups:
      Samchon:
        patterns:
          - "@nestia/*"
          - "nestia"
          - "tstl"
          - "typia"
          - "tgrid"
          - "prisma-markdown"
      NestJS:
        patterns:
          - "@nestjs/*"
      Prisma:
        patterns:
          - "@prisma/*"
          - "prisma"
      TypeScript:
        patterns:
          - "typescript"
          - "ts-patch"
#######################################################
  - package-ecosystem: 'npm'
    directory: '/packages/api'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 25
    # versioning-strategy: increase
    allow:
      - dependency-name: "@nestia/fetcher"
      - dependency-name: "typia"
    groups:
      Samchon:
        patterns:
          - "@nestia/fetcher"
          - "typia"
#######################################################